### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by OmarQataberi** [luanpotter/audioplayers#142]
Hey,
I can't figure out why the AudioCache can't load any asset for me.
 my code:
```
AudioCache audioCache = AudioCache(
    fixedPlayer: AudioPlayer()..setReleaseMode(ReleaseMode.STOP),
  ); 

audioCache.play('audio/3.mp3');
```
```
E/flutter (17763): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/audio/3.mp3
E/flutter (17763): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (17763): <asynchronous suspension>
E/flutter (17763): #1      AudioCache._fetchAsset (package:audioplayers/audio_cache.dart:57:29)
E/flutter (17763): <asynchronous suspension>
E/flutter (17763): #2      AudioCache.fetchToMemory (package:audioplayers/audio_cache.dart:64:30)
E/flutter (17763): <asynchronous suspension>
E/flutter (17763): #3      AudioCache.load (package:audioplayers/audio_cache.dart:79:37)
E/flutter (17763): <asynchronous suspension>
E/flutter (17763): #4      AudioCache.play (package:audioplayers/audio_cache.dart:97:23)
E/flutter (17763): <asynchronous suspension>
E/flutter (17763): #5      _ZaffatPlayerBarState.build.<anonymous closure> (package:zaffat/ui/widgets/zaffat_player_bar.dart:88:30)
E/flutter (17763): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (17763): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (17763): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter (17763): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
E/flutter (17763): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (17763): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter (17763): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (17763): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (17763): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (17763): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (17763): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (17763): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (17763): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (17763): #19     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (17763): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (17763): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (17763): #22     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (17763): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
E/flutter (17763): 

```

**Comment by minhvuongrbs** [comment]
Exactly what i hope to see in the future!

**Comment by minhvuongrbs** [comment]
Exactly what i hope to have! For now, to run local audio we have to combine path_provider library.

**Comment by minhvuongrbs** [comment]
You can find the solution from there (comment of Jawnnypoo)
https://github.com/rxlabz/audioplayer/issues/5

**Comment by erickzanardo** [comment]
@OmarQataberi  Have you put your asset on your pubspec?

like:

```
flutter:
  assets:
   - assets/audio/3.mp3
```

**Comment by minhvuongrbs** [comment]
yes, just need assets/audio instead of

**Comment by erickzanardo** [comment]
I don't understand, instead of what? Did you got this working?

**Comment by minhvuongrbs** [comment]
The solution i sent you will help you load or create assets file. In case you are still stuck, let me know and i will send you example via my Github.

**Comment by minhvuongrbs** [comment]
Or try this https://github.com/luanpotter/audioplayers/blob/master/doc/audio_cache.md

**Comment by OmarQataberi** [comment]
> @OmarQataberi Have you put your asset on your pubspec?
> 
> like:
> 
> ```
> flutter:
>   assets:
>    - assets/audio/3.mp3
> ```

Yes I did,
I figured out that the problem is that I missed a folder name instead of (audio/3.mp3) it is (audio/main/3.mp3) so... My bad

**Comment by erickzanardo** [comment]
Glad that you got this working! Thanks for reporting back

**Comment by minhvuongrbs** [comment]
> Glad that you got this working! Thanks for reporting back

I mistook you for the person who asked the question! sorry about that

**Comment by Nisa-fatima369** [comment]
I'm exactly facing the same issue of "unable to load the asset while there isn't any error with pubspec yaml file . I search alot almost implemented many posssibilities. can anyone help me in this scenario.

**Comment by ragulzaheer** [comment]
I/flutter (13912): Audio playback error: Unable to load asset: "assets/assets/1.mp3".
I/flutter (13912): The asset does not exist or has empty data.

i have this problem how  to solve it
