### ISSUE TITLE
AudioCache fails in 0.12.0 with issues in path_provider

### ISSUE THREAD

**Issue by agiratech-vigneshm** [luanpotter/audioplayers#167]
I am getting the following error when I am trying to play a local .wav file with audioCache, The file plays fine with the previous version of the plugin though. Here is the stack trace.

```
E/flutter (21344): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (21344): NoSuchMethodError: Class 'MethodChannel' has no instance method 'invokeMethod' with matching arguments.
E/flutter (21344): Receiver: Instance of 'MethodChannel'
E/flutter (21344): Tried calling: invokeMethod<String>("getTemporaryDirectory")
E/flutter (21344): Found: invokeMethod(String, [dynamic]) => Future<dynamic>
E/flutter (21344): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (21344): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:26:22)
E/flutter (21344): <asynchronous suspension>
E/flutter (21344): #2      AudioCache.fetchToMemory (package:audioplayers/audio_cache.dart:61:37)
E/flutter (21344): <asynchronous suspension>
E/flutter (21344): #3      AudioCache.load (package:audioplayers/audio_cache.dart:79:37)
E/flutter (21344): <asynchronous suspension>
E/flutter (21344): #4      AudioCache.play (package:audioplayers/audio_cache.dart:97:23)
E/flutter (21344): <asynchronous suspension>
E/flutter (21344): #5      XylophoneApp.build.<anonymous closure> (package:xylophone/main.dart:16:24)
E/flutter (21344): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (21344): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (21344): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (21344): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (21344): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (21344): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (21344): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (21344): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (21344): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (21344): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (21344): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (21344): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (21344): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (21344): #19     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (21344): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

The reproducible repo to the issue is [here](https://github.com/shivenigma/xylophone-flutter/commit/e6a89b203fa104805971f7190690400a4b019166)

**Comment by luanpotter** [comment]
Hi, @agiratech-vigneshm ! What version of flutter are you using?

Have you tried running flutter clean and the flutter pub get again?

The error is on both android and iOS?

**Comment by erickzanardo** [comment]
Closing due inactivity.
