### ISSUE TITLE
PlatformException: Unsupported value: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by phimath** [luanpotter/audioplayers#260]
I am getting this exception.  This occurs after an onPlayerCompletion event, during which I call to play the next audio file. 

Not sure what to do to troubleshoot?

Exception has occurred.
PlatformException (PlatformException(error, Unsupported value: java.lang.IllegalStateException, null))

`E/AudioplayersPlugin( 7084): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
E/AudioplayersPlugin( 7084): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:234)
E/AudioplayersPlugin( 7084): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:52)
E/AudioplayersPlugin( 7084): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:62)
E/AudioplayersPlugin( 7084): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:41)
E/AudioplayersPlugin( 7084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/AudioplayersPlugin( 7084): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/AudioplayersPlugin( 7084): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/AudioplayersPlugin( 7084): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 7084): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/AudioplayersPlugin( 7084): 	at android.os.Looper.loop(Looper.java:160)
E/AudioplayersPlugin( 7084): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AudioplayersPlugin( 7084): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 7084): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AudioplayersPlugin( 7084): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#xyz.luan/audioplayers( 7084): Failed to handle method call
E/MethodChannel#xyz.luan/audioplayers( 7084): java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalStateException
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#xyz.luan/audioplayers( 7084): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/EGL_emulation( 7084): eglMakeCurrent: 0xca4fc780: ver 2 0 (tinfo 0xc7247c80)`

**Comment by phimath** [comment]
I was able to sort this out.  The issue was that I was changing the event listeners on every track played instead of once for the audio player.
