### ISSUE TITLE
Unsupported value: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mar-sir** [luanpotter/audioplayers#353]
### The Error

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference, null)

### The Code

``` dart
  //播放
  Future play(String url, {Duration duration}) async {
    if (url == null || url.isEmpty) return;
    String str = Uri.encodeFull(url);
    print("===>\t" + str);

    int result =
        await _audioPlayer.play(Uri.encodeFull(url), position: duration);
    if (result == 1) {
      setState(() {
        _playerState = AudioPlayerState.PLAYING;
      });
    }
  }

```

**Comment by luanpotter** [comment]
in which line does the error happen? can `Uri.encodeFull` return null? have you instantiated your instance of `_audioPlayer`? can we get a full trace?

**Comment by mar-sir** [comment]
I have resolved this problem. The error happened in _audioPlayer.play() when I init _audioPlayer with PlayerMode.LOW_LATENCY mode in Android. Have no error when I replace mode with PlayerMode.MEDIA_PLAYER

**Comment by luanpotter** [comment]
That is weird, can you take a look @erickzanardo or @feroult ?

**Comment by luanpotter** [comment]
Also, @mar-sir, can you provide us with a stack trace? And the initialization part of your code?

**Comment by mar-sir** [comment]
### The Code
``` dart
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:io';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Music',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MusicWidget(),
    );
  }
}


class MusicWidget extends StatefulWidget {
  MusicWidget({Key key}) : super(key: key);

  @override
  _MusicWidgetPageState createState() => _MusicWidgetPageState();
}

class _MusicWidgetPageState extends State<MusicWidget> {

  AudioPlayer _audioPlayer = new AudioPlayer(mode: PlayerMode.LOW_LATENCY);


  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(

      appBar: AppBar(title: Text("Music")),
      body: Center(
        child: RaisedButton(onPressed: (){
          play("http://wx.yn12345.net/mp3/20191118/请问怎么查询房屋预售许可证？.mp3");
        },child: Text("play"),),
      ),
    );
  }
  

  //播放
  Future play(String url, {Duration duration}) async {
    if (url == null || url.isEmpty) return;
    int result =
    await _audioPlayer.play(Uri.encodeFull(url), position: duration);
    if (result == 1) {
      setState(() {

      });
    }
  }


  @override
  void dispose() {
    // TODO: implement dispose
    _audioPlayer?.stop();
    super.dispose();
  }
}

```

### The Error
``` dart
Launching lib/pages/test_page.dart on FRD AL00 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device FRD AL00...
I/hwaps   (14101): JNI_OnLoad
V/AudioManager(14101): playSoundEffect   effectType: 0
E/AudioAttributes(14101): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool(14101): App requested 100 channels
D/NetworkSecurityConfig(14101): No Network Security Config specified, using platform default
E/AudioplayersPlugin(14101): Unexpected error!
E/AudioplayersPlugin(14101): java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.java:297)
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.java:261)
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.java:255)
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.java:169)
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:64)
E/AudioplayersPlugin(14101): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:43)
E/AudioplayersPlugin(14101): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/AudioplayersPlugin(14101): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/AudioplayersPlugin(14101): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/AudioplayersPlugin(14101): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin(14101): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/AudioplayersPlugin(14101): 	at android.os.Looper.loop(Looper.java:144)
E/AudioplayersPlugin(14101): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AudioplayersPlugin(14101): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin(14101): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AudioplayersPlugin(14101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/MethodChannel#xyz.luan/audioplayers(14101): Failed to handle method call
E/MethodChannel#xyz.luan/audioplayers(14101): java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:46)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#xyz.luan/audioplayers(14101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter (14101): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference, null)
E/flutter (14101): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14101): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (14101): <asynchronous suspension>
E/flutter (14101): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:294:10)
E/flutter (14101): #3      AudioPlayer.play (package:audioplayers/audioplayers.dart:353:30)
E/flutter (14101): <asynchronous suspension>
E/flutter (14101): #4      _MusicWidgetPageState.play (package:province12345/pages/test_page.dart:73:24)
E/flutter (14101): <asynchronous suspension>
E/flutter (14101): #5      _MusicWidgetPageState.build.<anonymous closure> (package:province12345/pages/test_page.dart:62:11)
E/flutter (14101): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (14101): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (14101): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14101): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (14101): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (14101): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (14101): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (14101): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (14101): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (14101): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14101): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14101): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14101): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14101): #19     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (14101): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14101): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (14101): #22     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (14101): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (14101): 
Lost connection to device.

```

**Comment by dkashkin** [comment]
I bumped into a very similar issue when I switched the player mode to LOW_LATENCY on Android. Rolling back the mode got rid of the exception.

**Comment by fatihmert** [comment]
> I bumped into a very similar issue when I switched the player mode to LOW_LATENCY on Android. Rolling back the mode got rid of the exception.

Yes, this solved my problem, but I have a delay in playing the sound for a few seconds. For this reason I made LOW_LATENCY. 

I'm still dealing with this problem, not the location. Thanks for the preliminary information.

**Comment by chihung93** [comment]
Me too.

**Comment by essboyer** [comment]
Likewise for me on audioplayers 0.15.1 and Flutter 1.17.0 LOW_LATENCY mode caused a Platform Exception Java NullPointer. Removing LOW_LATENCY mode fixed it.

**Comment by Nash0x7E2** [comment]
@luanpotter Is there any update to this issue? I've been running to this error on Android. 

Here is the full stacktrace:
```
E/flutter (32475): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Unexpected error!, Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference
E/flutter (32475): 	at xyz.luan.audioplayers.WrappedMediaPlayer.getDuration(WrappedMediaPlayer.java:148)
E/flutter (32475): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:110)
E/flutter (32475): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/flutter (32475): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/flutter (32475): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (32475): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:650)
E/flutter (32475): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32475): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (32475): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (32475): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (32475): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32475): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (32475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (32475): )
E/flutter (32475): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (32475): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (32475): <asynchronous suspension>
E/flutter (32475): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (32475): #3      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319:10)
E/flutter (32475): #4      AudioPlayer.getDuration (package:audioplayers/audioplayers.dart:528:12)
E/flutter (32475): #5      AudioService._getDuration (package:junto_beta_mobile/screens/create/create_templates/audio_service.dart:124:41)
E/flutter (32475): #6      AudioService.playRecording.<anonymous closure> (package:junto_beta_mobile/screens/create/create_templates/audio_service.dart:116:9)
E/flutter (32475): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (32475): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (32475): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (32475): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (32475): #11     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (32475): #12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (32475): #13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (32475): #14     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (32475): #15     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (32475): #16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (32475): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (32475): #18     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (32475): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (32475): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (32475): #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (32475): #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (32475): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by SherazHussain110** [comment]
I face the same issue and I switch the player mode from **PlayerMode.LOW_LATENCY** to **PlayerMode.MEDIA_PLAYER** and it worked for me.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
