### ISSUE TITLE
MissingPluginException (No implementation found for method play ...)

### ISSUE THREAD

**Issue by smccleary** [luanpotter/audioplayers#40]
I have other plugins installed and even some custom ones with no issue, but this one constantly throws:

`MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)`

I have tried:
- removing and reinstalling
- making sure to run `flutter build ios`
- Development Pods are all public
- XCODE is not complaining about plugin it missing
- making sure to use `audioplayers: ^0.7.5` in the pubspec
- instantiated right using `AudioPlayer audioPlayer = new AudioPlayer();`
- flutter info up to date: `[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)`

What am I missing?

**Comment by smccleary** [comment]
Tried on new PC from scratch and same issue. Strange

**Comment by terrytangabc** [comment]
Same issue here, any solutions?

**Comment by terrytangabc** [comment]
The exception is thrown when you're doing hot reload or hot restart. I solved the problem by simply restarting the app

**Comment by dark-chocolate** [comment]
@smccleary When you first add the dependency in your project, you need to stop current session by tapping red Stop button in the IDE and then do full restart by tapping green Play Button.

**Comment by smccleary** [comment]
@terrytangabc thats what I ended up doing. thanks

**Comment by erickzanardo** [comment]
Closing this again, it was wrong referenced.

**Comment by sakina1403** [comment]
@terrytangabc I tried this many times. It works fine on Android emulator, but throws this error when I call the play method while running on iOS. Any suggestions?

```[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:211:10)
#2      AudioPlayer.play (package:audioplayers/audioplayers.dart:231:30)
<asynchronous suspension>
#3      _PlayerScreenState.build.<anonymous closure> (package:mind_detox/screens/player.dart:68:50)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#8      TapGestureRecognizer.handlePrimaryPointer (package:flutt<…>
```

**Output of flutter doctor -v**

```[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Users/sakina/development/flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/sakina/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 •
      Android 9 (API 28) (emulator)
    • iPhone X                  • 04F20877-53D7-4B61-8A64-4B02A16BF0D3 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!```

All suggestions appreciated. @erickzanardo

**Comment by evil-shrike** [comment]
Hi,

I'm having the same issue with simple code for playing local assets.
```
final player = AudioCache();
player.play('note1.wav');
```
I did restart my app. The error is happening while running the code in Android Emulator.

Any advice?

```
E/flutter (10670): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method startHeadlessService on channel xyz.luan/audioplayers)
E/flutter (10670): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (10670): <asynchronous suspension>
E/flutter (10670): #1      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:303:10)
E/flutter (10670): #2      new AudioPlayer (package:audioplayers/audioplayers.dart:287:5)
E/flutter (10670): #3      AudioCache._player (package:audioplayers/audio_cache.dart:84:31)
E/flutter (10670): #4      AudioCache.play (package:audioplayers/audio_cache.dart:95:26)
```

**Comment by naimurhasan** [comment]
I see the error but my audio still gets played, 
so I've commented the line to keep my log clean! 😢

// throw MissingPluginException('No implementation found for method $method on channel $name');

**Comment by alienbd** [comment]
gg

**Comment by alienbd** [comment]
I had the same problem earlier and found a solution on stackoverflow. https://stackoverflow.com/questions/58986260/flutter-aduioplayers-missingpluginexceptionno-implementation-found-for-method-s

apparently the problem was the introduced in version 0.13.3 
I just changed in pubspec.yaml file from 
`audioplayers: ^0.13.3`
to 

`audioplayers: 0.13.2`

as mentioned in the solution and it just worked fine for me. Thanks.

**Comment by nemoryoliver** [comment]
> I had the same problem earlier and found a solution on stackoverflow. https://stackoverflow.com/questions/58986260/flutter-aduioplayers-missingpluginexceptionno-implementation-found-for-method-s
> 
> apparently the problem was introduced in version 0.13.3
> I just changed in pubspec.yaml file from
> `audioplayers: ^0.13.3`
> to
> 
> `audioplayers: 0.13.2`
> 
> as mentioned in the solution .
> 
> It just worked fine for me. Thanks.

Great to hear! How about in version 0.13.4?

**Comment by elznr** [comment]
I have still same problem on audioplayers: 0.15.0

**Comment by oseiasmribeiro** [comment]
Same problem on audioplayer: 1.0.3
MissingPluginException (MissingPluginException(No implementation found for method initService on channel flutter_radio_player))

**Comment by ashishpatel1992** [comment]
I am getting following error. My version is 0.15.1


```
E/flutter (14398): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method setNotification on channel xyz.luan/audioplayers)
E/flutter (14398): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (14398): <asynchronous suspension>
E/flutter (14398): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (14398): #2      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319:10)
E/flutter (14398): #3      AudioPlayer.setNotification (package:audioplayers/audioplayers.dart:495:12)
E/flutter (14398): #4      _RadioTestState.play (package:tsqradio/Radio_test.dart:28:17)
E/flutter (14398): <asynchronous suspension>
E/flutter (14398): #5      _RadioTestState.build.<anonymous closure>.<anonymous closure> (package:tsqradio/Radio_test.dart:76:23)
E/flutter (14398): #6      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
E/flutter (14398): #7      _RadioTestState.build.<anonymous closure> (package:tsqradio/Radio_test.dart:69:19)
E/flutter (14398): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (14398): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (14398): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14398): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (14398): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (14398): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (14398): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter (14398): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (14398): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (14398): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (14398): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (14398): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (14398): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (14398): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14398): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14398): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14398): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14398): #25     _rootRunUnary (dart:async/zone.dart:1159:13)
E/flutter (14398): #26     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
E/flutter (14398): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
E/flutter (14398): #28     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (14398): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

**Comment by hemantcloud** [comment]
> 

can we edit the pre defined files in flutter

**Comment by ZdenekKrcal** [comment]
I have same issue:

Uncaught MissingPluginException(No implementation found for method create on channel xyz.luan/audioplayers)

It works in debug on the web but when I buid app (flutter build web --web-renderer canvaskit) it doesnt work on the production.

**Comment by Gustl22** [comment]
@ZdenekKrcal try a `flutter clean` before.

**Comment by XaverStiensmeier** [comment]
I have the same issue on ubuntu22.04 seems like Linux is not supported fully.

**Comment by Gustl22** [comment]
@XaverStiensmeier it runs quite well on linux, see our tests: https://github.com/bluefireteam/audioplayers/actions/runs/8340549092/job/22824902280

Notice the requirements: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers_linux#setup-for-linux
