### ISSUE TITLE
on web it works in debug but not in production

### ISSUE THREAD

**Issue by lukepighetti** [luanpotter/audioplayers#482]
I am importing my app as a package so I can render it in a marketing website. I've had to change the root path of my assets to `../packages/ptp/assets/tones/`. This works in debug mode but as soon as I deploy it to production `audioplayers` stops working and I get these errors in chrome

```
js_helper.dart:1343 Uncaught PlatformException(error, NoSuchMethodError: method not found: 'Oj' (J.aC(...).Oj is not a function), null)
    at Object.c (https://partimerpro.app/main.dart.js:1873:3)
    at Q6.zM (https://partimerpro.app/main.dart.js:36963:14)
    at https://partimerpro.app/main.dart.js:37011:93
    at Xa.a (https://partimerpro.app/main.dart.js:3128:71)
    at Xa.$2 (https://partimerpro.app/main.dart.js:21031:23)
    at Wx.$1 (https://partimerpro.app/main.dart.js:21023:30)
    at Ej.tN (https://partimerpro.app/main.dart.js:21847:40)
    at Ej.jg (https://partimerpro.app/main.dart.js:21849:30)
    at Tj.$0 (https://partimerpro.app/main.dart.js:21350:13)
    at Object.nb (https://partimerpro.app/main.dart.js:3242:41)
```

**Comment by luanpotter** [comment]
thanks for pointing it out @lukepighetti . @erickzanardo has just told me the same thing. I investigating why it would be the case.

**Comment by rodydavis** [comment]
Getting that for me too, Tried debugging but wasnt sure the reason. I think it has something to do with the Audio Context though

**Comment by erickzanardo** [comment]
This is fixed on 0.15.1-beta, a full release should be out soon, but you can use the beta in the meanwhile.

https://pub.dev/packages/audioplayers/versions/0.15.1-beta

**Comment by rodydavis** [comment]
Beta worked perfectly!! https://pitchpipe.app/ Thank you :)

**Comment by rodydavis** [comment]
Also using it here for this curious: https://rodydavis.github.io/creative_engineering

**Comment by erickzanardo** [comment]
The fix is live on https://pub.dev/packages/audioplayers/versions/0.15.1
