### ISSUE TITLE
The getter '_nextController' was called on null.

### ISSUE THREAD

**Issue by hrongyong** [luanpotter/audioplayers#583]
I added two Stream at  audioplayers.dart，Used to monitor the click event of the ios notification bar。
I wrote according to onPlayerCompletion writing method, but the above problem appeared。

![image](https://user-images.githubusercontent.com/37935622/88006693-d4fd4380-cb3e-11ea-9391-5cd4f5b3b26d.png)
![image](https://user-images.githubusercontent.com/37935622/88006705-dcbce800-cb3e-11ea-9fdd-c1e3c2f05da1.png)
![image](https://user-images.githubusercontent.com/37935622/88006753-fc541080-cb3e-11ea-8199-8e92f8e16c79.png)
![image](https://user-images.githubusercontent.com/37935622/88006807-21e11a00-cb3f-11ea-87d2-5a83e8774f86.png)

2020-07-21 10:35:00.103918+0800 Runner[1142:420672] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter '_nextController' was called on null.
Receiver: null
Tried calling: _nextController
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AudioPlayer._doHandlePlatformCall (package:audioplayers/audioplayers.dart:639:18)
#2      AudioPlayer.platformCallHandler (package:audioplayers/audioplayers.dart:573:7)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#10     _invoke3 (dart:ui/hooks.dart:289:10)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)

**Comment by hrongyong** [comment]
Ok fine。is my problem。I forgot to carry playerId parameter when I sent it back on the ios side
