### ISSUE TITLE
setContainerResult error, url=clientSearch

### ISSUE THREAD

**Issue by xwangly** [luanpotter/audioplayers#622]
在进入Futter页面后再返回，不断的试几次，出现了如下崩溃

flutter_boost：v1.17.1-hotfixes
flutter:1.17

java.lang.RuntimeException: Unable to destroy activity {com.design.employee.dev/com.tfzq.flutter.TFlutterActivity}: java.lang.RuntimeException: setContainerResult error, url=clientSearch
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5001)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5030)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.RuntimeException: setContainerResult error, url=clientSearch
        at com.idlefish.flutterboost.Debuger.exception(:53)
        at com.idlefish.flutterboost.FlutterViewContainerManager.setContainerResult(:98)
        at com.idlefish.flutterboost.ContainerRecord.onDestroy(:136)
        at com.idlefish.flutterboost.containers.FlutterActivityAndFragmentDelegate.onDestroyView(:217)
        at com.tfzq.flutter.TFlutterActivity.onDestroy(:286)
        at android.app.Activity.performDestroy(Activity.java:8180)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4986)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5030) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-09-07 11:05:59.426 32724-32724/com.design.employee.dev E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by erickzanardo** [comment]
There isn't enough information on this issue for us to act on. Please edit this, or open a new one and please follow the issue template.

Feel free to comment here and we can re open this eventually.
