### ISSUE TITLE
 [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception: E/flutter ( 2586): MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers) E/flutter ( 2586): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7) E/flutter ( 2586): <asynchronous suspension> E/flutter ( 2586): #1      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:80:10) E/flutter ( 2586): #2      AudioPlayer.play (package:audioplayers/audioplayers.dart:86:12) E/flutter ( 2586): #3      VoicePlayer.playReceiveSound (package:tunnel/utils/voice_utils.dart:47:17)

### ISSUE THREAD

**Issue by jinfagang** [luanpotter/audioplayers#64]
```
 [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 2586): MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)
E/flutter ( 2586): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 2586): <asynchronous suspension>
E/flutter ( 2586): #1      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:80:10)
E/flutter ( 2586): #2      AudioPlayer.play (package:audioplayers/audioplayers.dart:86:12)
E/flutter ( 2586): #3      VoicePlayer.playReceiveSound (package:tunnel/utils/voice_utils.dart:47:17)
```

**Comment by matthewrice345** [comment]
I have the same error. Started happening after upgrading to Flutter 1.0.

**Comment by jinfagang** [comment]
@matthewrice345  My problem solved, just run flutter clean to clean build, it's cache problem

**Comment by luanpotter** [comment]
Thanks for the solution, @jinfagang ! If similar problems occur, please feel free to open new issues.

**Comment by matthewrice345** [comment]
My issue looked like an issue with **audioplayers** but was totally unrelated. When building in XCode the error manifested itself in this dependency but is due to some build scheme issue with Flutter. 
[Issue](https://github.com/flutter/flutter/issues/24641)
