### ISSUE TITLE
play() throws PlatfomException

### ISSUE THREAD

**Issue by rgb1380** [luanpotter/audioplayers#643]
If AudioPlayer is initialised using low latency mode, play() fails with an exception when resource is on the Internet

**Code to Reproduce**
```dart
AudioPlayer audioPlayer = AudioPlayer(mode: PlayerMode.LOW_LATENCY);    // Using AudioPlayer() without the mode has no issue
 audioPlayer.play(url)      // Use a url pointing to a remote audio file
```

**Log Errors**
The following error is thrown:

Exception has occurred.
PlatformException (PlatformException(Unexpected error!, Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
	at xyz.luan.audioplayers.WrappedSoundPool.downloadUrl(WrappedSoundPool.java:318)
	at xyz.luan.audioplayers.WrappedSoundPool.loadTempFileFromNetwork(WrappedSoundPool.java:282)
	at xyz.luan.audioplayers.WrappedSoundPool.getAudioPath(WrappedSoundPool.java:276)
	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.java:173)
	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:81)
	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:60)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
, null))

**Platforms**
This was tested on a physical device Android 10

**Comment by luanpotter** [comment]
What URL??

> **Files/URLs/Sources**
If your issue or bug involves specific files, you must provide them. If they are URLs they should already be somewhere in the code provided but please replicate those here. If they are private URLs or actual files, please upload them somewhere accessible and add them here. If your issue is with a stream, for example, provide the stream link or if the stream is private, create a similar stream that also causes the problem and is public, and add that. If you don't know if your issue involves specific resources, please download a few of the [mp3 sample files](https://github.com/luanpotter/audioplayers/tree/master/example/assets) present in the `example` app and test with those instead of whatever you are doing currently. If the issue persists, it does not involve specific files. Otherwise, this section is **mandatory**.

Please read the description carefully before opening any issues.

**Comment by rgb1380** [comment]
> What URL??
The actual url does not make difference. As I explained in the error description set the URL a resource accessible on the web. The issue is that if the player is instantiated with mode: PlayerMode.LOW_LATENCY, you get the exception and if it is not it works find (obviously with a valid URL). Hope this is clear enough.

> Please read the description carefully before opening any issues.
I had read the description. The issue is not related to a specific file or URL. I did not intend to waste your time. If you do not wish to investigate it is your decision.

**Comment by Dobbychen** [comment]
Same issue here: `PlayerMode.LOW_LATENCY` cause the error in Android

**Comment by binhbk230** [comment]
I have same issue on ios when playing audio from internet. It work fine on android

**Comment by psrcek** [comment]
Still not fixed in the latest release, I have the same issue.

**Comment by erickzanardo** [comment]
Closing this due to reports of this being fixed on newer versions. Feel free to open a new issue in case of this still happening
