### ISSUE TITLE
Dom Exception on playing some urls on web

### ISSUE THREAD

**Issue by iampawan** [luanpotter/audioplayers#693]
NotSupportedError: Failed to load because no supported source was found.

This looks like CORS issue.

`Error: NotSupportedError: Failed to load because no supported source was found.

    at Object.createErrorWithStack (http://localhost:52022/dart_sdk.js:4365:12)
    at Object._rethrow (http://localhost:52022/dart_sdk.js:38257:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52022/dart_sdk.js:38251:13)
    at Object._microtaskLoop (http://localhost:52022/dart_sdk.js:38083:13)
    at _startMicrotaskLoop (http://localhost:52022/dart_sdk.js:38089:13)
    at http://localhost:52022/dart_sdk.js:33586:9`

**Comment by luanpotter** [comment]
if it's a CORs issue it's not audioplayesr fault, you need to fix the server to enable cors. do you have an example url that doesn't work?

**Comment by whatthemehek** [comment]
I am having the same error- it appears when I try to use AudioCache to play local mp3s, but does not appear when playing wav files.

**Comment by erickzanardo** [comment]
Closing due inactivity. CORS indeed isn't Audioplayers fault
