### ISSUE TITLE
Performing playback under the web, the following exception was thrown

### ISSUE THREAD

**Issue by stoneLee81** [luanpotter/audioplayers#713]
PlatformException(error, NoSuchMethodError: invalid member on null: 'currentTime', null, null)
    at Object.throw_ [as throw] (http://localhost:50276/dart_sdk.js:4328:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:50276/packages/flutter/src/services/system_channels.dart.lib.js:782:19)
====itempage====
###Lcfarm###  v  ====msgdtl==== false -1 false 7
###Lcfarm###  v  ====msgdtl==== false -1 false 7
====itempage====

════════ Exception caught by widgets library ═══════════════════════════════════
NoSuchMethodError: invalid member on null: 'dispose'
════════════════════════════════════════════════════════════════════════════════
###Lcfarm###  v  ====msgdtl==== false -1 false 7
====itempage====

════════ Exception caught by widgets library ═══════════════════════════════════
NoSuchMethodError: invalid member on null: 'dispose'
════════════════════════════════════════════════════════════════════════════════
Error: PlatformException(error, NoSuchMethodError: invalid member on null: 'currentTime', null, null)
    at MethodChannel._invokeMethod (http://localhost:50276/packages/flutter/src/services/system_channels.dart.lib.js:944:32)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50276/dart_sdk.js:37593:33
    at _RootZone.runUnary (http://localhost:50276/dart_sdk.js:37447:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50276/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:50276/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:50276/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:50276/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50276/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:50276/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:50276/dart_sdk.js:37714:13)
    at http://localhost:50276/dart_sdk.js:33226:9

**Comment by stoneLee81** [comment]
@luanpotter

**Comment by erickzanardo** [comment]
As stated on the [README](https://github.com/luanpotter/audioplayers#controlling), this is not available on web yet
