### ISSUE TITLE
PlatformException (PlatformException(Unexpected error!, Operation is not supported for read-only collection, java.lang.UnsupportedOperationException: Operation is not supported for read-only collection

### ISSUE THREAD

**Issue by coder-Aayush** [luanpotter/audioplayers#717]
I am trying to play audio play using audioplayers plugin but I am getting unexpected error.

**Code to Reproduce**
```
void player({@required String audioPathFromFirebase}) async {
    await _audioPlayer.play(
      audioPathFromFirebase,
    );
  }
```

**Log Errors**
PlatformException (PlatformException(Unexpected error!, Operation is not supported for read-only collection, java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
	at kotlin.collections.EmptyMap.put(Unknown Source:4)
	at java.util.Collections$SynchronizedMap.put(Collections.java:2639)
	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:247)
	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:62)
	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
, null))

* flutter version: latest
* audioplayers version: ^0.17.0 and ^0.17.1

**Comment by squashmode** [comment]
I get this too on Android on version 0.17.1, after updating flutter to the latest beta:.  One other piece of information is that after upgrading flutter, I had up change the minSdk in my project from 16 to 23, because of this error:
```
uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [:audioplayers] 
```

Flutter version:
```
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (3 weeks ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

**Comment by VictorUvarov** [comment]
This might help https://stackoverflow.com/questions/55654568/android-studio-unsupportedoperationexception-operation-is-not-supported-for
