### ISSUE TITLE
[Android] Playing Sample 4 (Remote) throws error!

### ISSUE THREAD

**Issue by VictorUvarov** [luanpotter/audioplayers#721]
Clicking play on sample 4 throws an error. `Operation is not supported for read-only collection`

**Full Description**
Looks like you're trying to use an unsupported method on a read only collection. 

**Code to Reproduce**
- Run the example app on android
- Click play on sample 4 in the remote tab

**Log Errors**
```
E/AudioAttributes( 7530): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool( 7530): App requested 100 channels
E/AudioplayersPlugin( 7530): Unexpected error!
E/AudioplayersPlugin( 7530): java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
E/AudioplayersPlugin( 7530): 	at kotlin.collections.EmptyMap.put(Unknown Source:4)
E/AudioplayersPlugin( 7530): 	at java.util.Collections$SynchronizedMap.put(Collections.java:2639)
E/AudioplayersPlugin( 7530): 	at xyz.luan.audioplayers.WrappedSoundPool.setUrl(WrappedSoundPool.kt:247)
E/AudioplayersPlugin( 7530): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:62)
E/AudioplayersPlugin( 7530): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:37)
E/AudioplayersPlugin( 7530): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 7530): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 7530): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/AudioplayersPlugin( 7530): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 7530): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AudioplayersPlugin( 7530): 	at android.os.Looper.loop(Looper.java:174)
E/AudioplayersPlugin( 7530): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AudioplayersPlugin( 7530): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 7530): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AudioplayersPlugin( 7530): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Files/URLs/Sources**
The sample 4 used in the example:  `const kUrl1 = 'https://luan.xyz/files/audio/ambient_c_motion.mp3';`

**Screenshots**
If applicable, add screenshots or video recordings to help explain your problem. This is totally optional.

**Platforms**
* OS: android
* OS version: android 10
* Device: emulator
* flutter version: Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8).
* audioplayers version: 0.17.1 (example app of master branch)
* release or not release: not release.
* Seems to only be an android problem.

**Comment by VictorUvarov** [comment]
Duplicate of #717
