### ISSUE TITLE
plugin does not work on emulator - setDataSource failed

### ISSUE THREAD

**Issue by Yowims** [luanpotter/audioplayers#824]
**Full Description**
When I'm trying to use audioplayers in my Android Studio's emulated smartphone, it raises me a **java.io.IOException : setDataSource failed** and the sound is not played.

**Code to Reproduce**
- using **flutter_audio_query** package to get musics from device;
- play music using **audioplayers** with the **filepath** property of our music

```
 final FlutterAudioQuery audioQuery = FlutterAudioQuery();

 AudioPlayer audioPlugin = AudioPlayer();

_loadSounds() async {
    setState(() {
      _isSearching = true;
    });
    try {
      songs = await audioQuery.getSongs();
      displayedSongs = songs;
    } on PlatformException {
      accessDenied = true;
    }

    setState(() {
      _isSearching = false;
    });
 }

audioPlugin.play(displayedSongs[index].filePath);
```

This is working fine with my physical device, but not with the emulator.

**Log Errors**
```

E/AudioplayersPlugin(16460): Unexpected error!
E/AudioplayersPlugin(16460): java.io.IOException: setDataSource failed.
E/AudioplayersPlugin(16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1191)
E/AudioplayersPlugin(16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
E/AudioplayersPlugin(16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
E/AudioplayersPlugin(16460): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
E/AudioplayersPlugin(16460): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AudioplayersPlugin(16460): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AudioplayersPlugin(16460): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin(16460): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin(16460): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin(16460): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin(16460): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/AudioplayersPlugin(16460): 	at android.os.Looper.loop(Looper.java:160)
E/AudioplayersPlugin(16460): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AudioplayersPlugin(16460): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin(16460): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AudioplayersPlugin(16460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (16460): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(Unexpected error!, setDataSource failed., java.io.IOException: setDataSource failed.
E/flutter (16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1191)
E/flutter (16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1164)
E/flutter (16460): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1131)
E/flutter (16460): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
E/flutter (16460): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/flutter (16460): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/flutter (16460): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (16460): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (16460): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (16460): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16460): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (16460): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (16460): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (16460): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16460): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (16460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (16460): , null)
E/flutter (16460): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter (16460): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (16460): <asynchronous suspension>
E/flutter (16460): #2      AudioPlayer._invokeMethod.<anonymous closure> (package:audioplayers/audioplayers.dart)
package:audioplayers/audioplayers.dart:1
E/flutter (16460): <asynchronous suspension>
E/flutter (16460):

```

**Platforms**

* OS: Android
* OS version: 28
* Device: Android Emulator - Pixel 2 API 28
* flutter doctor output :

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [version 10.0.19042.870], locale fr-FR)
    • Flutter version 2.0.3 at C:\flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\ANDROID_SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\ANDROID_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\***\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

* audioplayers version: **0.18.1**

**Comment by erickzanardo** [comment]
Please, can you confirm that the path returned by this other plugin points to an existing file on the emulator?

On our example app we have tests for files in the device storage and last time I checked it was working fine on both devices and emulators.

**Comment by erickzanardo** [comment]
Closing due inactivity, if you have more info to add to the issue, just comment here and we can re open the issue.
