### ISSUE TITLE
Not playing external url

### ISSUE THREAD

**Issue by OperKH** [luanpotter/audioplayers#84]
After upgrading to audioplayers: ^0.8.0 it can't play internet radio. But if I downgrade to audioplayers: 0.7.8 it works OK.

Here is logs:
```
I/flutter ( 6375): AudioPlayerState.PLAYING
V/MediaHTTPService( 6375): makeHTTPConnection: CookieHandler (java.net.CookieManager@8e0a860) exists.
V/MediaHTTPService( 6375): makeHTTPConnection(android.media.MediaHTTPService@b22c803): cookieHandler: java.net.CookieManager@8e0a860 Cookies: null
W/MediaPlayerNative( 6375): Stream has no duration and is therefore not seekable.
E/MediaPlayerNative( 6375): error (-2147483648, 0)
E/MediaPlayerNative( 6375): Attempt to call getDuration in wrong state: mPlayer=0x8d3f2160, mCurrentState=0
E/MediaPlayerNative( 6375): error (-38, 0)
E/MediaPlayer( 6375): Error (-2147483648,0)
E/MediaPlayerNative( 6375): stop called in state 0, mPlayer(0x8d3f2160)
E/MediaPlayerNative( 6375): error (-38, 0)
I/flutter ( 6375): 1:37:12.704000
V/MediaPlayer( 6375): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 6375): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 6375): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 6375): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter ( 6375): AudioPlayerState.COMPLETED
```

**Comment by OperKH** [comment]
ALso there is bugs on iOS.

![simulator screen shot - iphone x - 2019-01-11 at 10 50 03](https://user-images.githubusercontent.com/13971093/51023375-6e818780-158f-11e9-98e2-00b6e9e22fab.png)

Here is logs:
```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.                                            6.7s
iOS => call play, playerId bb850e80-5443-4501-b2e9-cc6fb4466324
play!
isLocal: 0 0
volume: 1.000000 1
position: 0.000000 (null)
setUrl http://radio.bloger.fm:8002/blogerfm-256
[C1.1 C14F9CFE-2225-41B4-81AC-DB1E0FC49D7E 192.168.88.147:50807<->176.9.125.38:8002]
Connected Path: satisfied (Path is satisfied), interface: en0
Duration: 0.306s, DNS @0.003s took 0.017s, TCP @0.024s took 0.000s
bytes in/out: 3169/311, packets in/out: 3/1, rtt: 0.041s, retransmitted packets: 0, out-of-order packets: 0
"LocalDataTask <E965C76E-1552-416A-B5CD-292C99BE50DE>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <E965C76E-1552-416A-B5CD-292C99BE50DE>.<1>, NSLocalizedDescription=cancelled} [-999]
player status: 1
ios -> updateDuration...nan
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building PlayerWidget(dirty, state:
flutter: _PlayerWidgetState#b8199):
flutter: The getter 'inMilliseconds' was called on null.
flutter: Receiver: null
flutter: Tried calling: inMilliseconds
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      _PlayerWidgetState.build (package:audioplayers_example/player_widget.dart:88:64)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #11     _invoke (dart:ui/hooks.dart:154:13)
flutter: #12     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderFlex overflowed by 99641 pixels on the bottom.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'inMilliseconds' was called on null.
```

**Comment by erickzanardo** [comment]
@OperKH this was resolved by your PR right?

**Comment by OperKH** [comment]
Yep! Closing because #85 already merged.
