### ISSUE TITLE
Didn't find class "android.media.MediaDataSource"

### ISSUE THREAD

**Issue by anishsumra** [luanpotter/audioplayers#866]
<addr>
 FATAL EXCEPTION: main

```diff

E/AndroidRuntime( 6612): Process: com.tictac.wrteam.TicTacToe, PID: 6612 
E/AndroidRuntime( 6612): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/media/MediaDataSource;
E/AndroidRuntime( 6612): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:42)
E/AndroidRuntime( 6612): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AndroidRuntime( 6612): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AndroidRuntime( 6612): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 6612): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 6612): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 6612): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 6612): 	at android.os.MessageQueue.next(MessageQueue.java:148)
E/AndroidRuntime( 6612): 	at android.os.Looper.loop(Looper.java:151)
E/AndroidRuntime( 6612): 	at android.app.ActivityThread.main(ActivityThread.java:5637)
E/AndroidRuntime( 6612): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6612): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6612): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime( 6612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
- E/AndroidRuntime( 6612): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.media.MediaDataSource" on path: DexPathList[[zip file "/data/app/com.tictac.wrteam.TicTacToe-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tictac.wrteam.TicTacToe-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime( 6612): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 6612): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 6612): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 6612): 	... 14 more
E/AndroidRuntime( 6612): 	Suppressed: java.lang.ClassNotFoundException: android.media.MediaDataSource
E/AndroidRuntime( 6612): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 6612): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 6612): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 6612): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 6612): 		... 15 more
- E/AndroidRuntime( 6612): 	**Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available**
D/NativeCrypto( 6612): ssl=0xb75b4e78 sslWrite buf=0xb717a528 len=7 write_timeout_millis=0
D/NativeCrypto( 6612):  sslNotify, appData=0xb76b4f30 ret=1
D/NativeCrypto( 6612):  sslSelect, appData=0xb76b4f30 woken up by a token
D/NativeCrypto( 6612):  sslSelect, appData=0xb76b4f30 read ret=1
I/Process ( 6612): Sending signal. PID: 6612 SIG: 9
! Lost connection to device.
```

</addr>

here i am facing issue with play method of Audioplayers in flutter

**Comment by erickzanardo** [comment]
This should have been fixed by https://github.com/luanpotter/audioplayers/pull/841 on `0.19.0`.
