### ISSUE TITLE
Not working on Android: java.io.IOException: setDataSource failed

### ISSUE THREAD

**Issue by bakwc** [luanpotter/audioplayers#900]
Audio not playing on android

**Full Description**
Created player and run play. Expected to hear sound. Got error instead.

**Code to Reproduce**
1) Add file to assets:
```
  assets:
    - assets/myfile.mp3
```
2) Try to play:
```
AudioPlayer audioPlayer = AudioPlayer();
await audioPlayer.play("assets/myfile.mp3", isLocal: true);
```

3) Also try to play:
```
AudioPlayer audioPlayer = AudioPlayer();
await audioPlayer.play("myfile.mp3", isLocal: true);
```

**Log Errors**
```
E/AudioplayersPlugin( 8054): Unexpected error!
E/AudioplayersPlugin( 8054): java.io.IOException: setDataSource failed.
E/AudioplayersPlugin( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1168)
E/AudioplayersPlugin( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1141)
E/AudioplayersPlugin( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1108)
E/AudioplayersPlugin( 8054): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
E/AudioplayersPlugin( 8054): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AudioplayersPlugin( 8054): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AudioplayersPlugin( 8054): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 8054): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 8054): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 8054): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 8054): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/AudioplayersPlugin( 8054): 	at android.os.Looper.loop(Looper.java:142)
E/AudioplayersPlugin( 8054): 	at android.app.ActivityThread.main(ActivityThread.java:6592)
E/AudioplayersPlugin( 8054): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 8054): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AudioplayersPlugin( 8054): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
E/flutter ( 8054): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Unexpected error!, setDataSource failed., java.io.IOException: setDataSource failed.
E/flutter ( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1168)
E/flutter ( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1141)
E/flutter ( 8054): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1108)
E/flutter ( 8054): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:37)
E/flutter ( 8054): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/flutter ( 8054): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/flutter ( 8054): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8054): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 8054): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 8054): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8054): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter ( 8054): 	at android.os.Looper.loop(Looper.java:142)
E/flutter ( 8054): 	at android.app.ActivityThread.main(ActivityThread.java:6592)
E/flutter ( 8054): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8054): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/flutter ( 8054): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
E/flutter ( 8054): , null)
E/flutter ( 8054): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter ( 8054): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 8054): <asynchronous suspension>
E/flutter ( 8054): #2      AudioPlayer._invokeMethod (package:audioplayers/src/audioplayer.dart:149:20)
E/flutter ( 8054): <asynchronous suspension>
E/flutter ( 8054): #3      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:171:20)
E/flutter ( 8054): <asynchronous suspension>
E/flutter ( 8054): #4      RacePageState.initAsync (package:FlyBox/screens/race_screen.dart:275:5)
E/flutter ( 8054): <asynchronous suspension>
E/flutter ( 8054): 

```

**Platforms**
Library version: 0.19.0
OS: Android 8.0.0
Device: Moto Z Play

**Comment by erickzanardo** [comment]
As stated on the [README](https://github.com/luanpotter/audioplayers#playing-audio to play local assets, you need to use audiocache.

**Comment by anasssanba1** [comment]
ihave the same issue

**Comment by AKA-LinCoder** [comment]
20250110 same
