### ISSUE TITLE
Fatal exception on Android API < 21 in WrappedMediaPlayer.kt setAttributes

### ISSUE THREAD

**Issue by Tregan** [luanpotter/audioplayers#928]
When we try to play audio using AudioCache on an Android device (both emulator and real device) with API < 21, we see native errors (see logs below)

**Full Description**
Looking into the error it's clear what's causing the issue. In `WrappedMediaPlayer.kt` there is no Android version check in `setAttributes`. This results in the following call:
```
player.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(usage)
                    .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                    .build()
            )
```
`MediaPlayer.setAudioAttributes` and `AudioAttributes.Builder()` aare not supported on API < 21. I noticed that in earlier versions of AudioPlayers, there WAS a check in this function, and the whole function looked like this (AudioPlayer 0.17.0, WrappedMediaPlayer.java):
```
@SuppressWarnings("deprecation")
    private void setAttributes(MediaPlayer player, Context context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            if (objectEquals(this.playingRoute, "speakers")) {
                player.setAudioAttributes(new AudioAttributes.Builder()
                        .setUsage(respectSilence ? AudioAttributes.USAGE_NOTIFICATION_RINGTONE : AudioAttributes.USAGE_MEDIA)
                        .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                        .build()
                );
            } else {
                // Works with bluetooth headphones
                // automatically switch to earpiece when disconnect bluetooth headphones
                player.setAudioAttributes(new AudioAttributes.Builder()
                        .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
                        .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                        .build()
                );
                if (context != null) {
                    AudioManager mAudioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
                    mAudioManager.setSpeakerphoneOn(false);
                }
            }

        } else {
            // This method is deprecated but must be used on older devices
            if (objectEquals(this.playingRoute, "speakers")) {
                player.setAudioStreamType(respectSilence ? AudioManager.STREAM_RING : AudioManager.STREAM_MUSIC);
            } else {
                player.setAudioStreamType(AudioManager.STREAM_VOICE_CALL);
            }
        }
    }
```
According to the [Feature parity table](https://github.com/luanpotter/audioplayers/blob/master/feature_parity_table.md) everything we use in our app should be supported. We don't use LLM, so it would be lovely if the above checks could be added back in! In Kotlin that would probably look something like this:
```
private fun setAttributes(player: MediaPlayer) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            val usage = when {
                // Works with bluetooth headphones
                // automatically switch to earpiece when disconnect bluetooth headphones
                playingRoute != "speakers" -> AudioAttributes.USAGE_VOICE_COMMUNICATION
                respectSilence -> AudioAttributes.USAGE_NOTIFICATION_RINGTONE
                else -> AudioAttributes.USAGE_MEDIA
            }
            player.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(usage)
                    .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                    .build()
            )
            if (usage == AudioAttributes.USAGE_VOICE_COMMUNICATION) {
                audioManager.isSpeakerphoneOn = false
            }
        } else {
            // This method is deprecated but must be used on older devices
            if (playingRoute == "speakers") {
                player.setAudioStreamType(if (respectSilence) AudioManager.STREAM_RING else AudioManager.STREAM_MUSIC)
            } else {
                player.setAudioStreamType(AudioManager.STREAM_VOICE_CALL)
            }
        }
    }
```

**Code to Reproduce**
We play audio the following way:
```
final AudioCache audioCache = AudioCache(prefix: 'assets/audio/');
await audioCache.loadAll([<filenames>]);

audioCache.play(fileName);
```

**Log Errors**
```
E/AndroidRuntime( 2666): FATAL EXCEPTION: main
E/AndroidRuntime( 2666): java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setAttributes(WrappedMediaPlayer.kt:361)
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.WrappedMediaPlayer.createPlayer(WrappedMediaPlayer.kt:346)
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.WrappedMediaPlayer.getOrCreatePlayer(WrappedMediaPlayer.kt:69)
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.kt:36)
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.kt:59)
E/AndroidRuntime( 2666): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.kt:34)
E/AndroidRuntime( 2666): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 2666): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 2666): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 2666): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 2666): 	at android.os.MessageQueue.next(MessageQueue.java:132)
E/AndroidRuntime( 2666): 	at android.os.Looper.loop(Looper.java:124)
E/AndroidRuntime( 2666): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 2666): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2666): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 2666): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 2666): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2666): 	at dalvik.system.NativeStart.main(Native Method)
```

**Platforms**
* OS: android
* OS version: < 21
* Device: both emulator and real device
* flutter version: 2.2.2
* audioplayers version: 0.19.0

**Comment by talent-apps** [comment]
We also see this crash in production.

**Comment by luanpotter** [comment]
@talent-apps sgtm, would you like to make a PR?

**Comment by julienduchow** [comment]
Same problem, is there any workaround currently for Android devices < 21?

**Comment by julienduchow** [comment]
I directly changed the lib code like @Tregan and @talent-apps suggested and it worked fine. I could make a PR for it. @luanpotter
